#!/bin/sh
set -eu
cmake -S . -B build -G Ninja -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DJPEGXL_ENABLE_BENCHMARK=OFF -DJPEGXL_ENABLE_EXAMPLES=OFF -DJPEGXL_ENABLE_FUZZERS=OFF -DJPEGXL_ENABLE_MANPAGES=OFF -DJPEGXL_ENABLE_SJPEG=OFF -DJPEGXL_ENABLE_TOOLS=OFF -DJPEGXL_ENABLE_VIEWERS=OFF -DJPEGXL_ENABLE_SKCMS=OFF -DJPEGXL_FORCE_SYSTEM_BROTLI=ON -DJPEGXL_FORCE_SYSTEM_HWY=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build build --target jxl --parallel 2 --verbose
mkdir harness-build
c++ $CXXFLAGS -c "$HARNESS_MAIN" -o harness-build/harness_main.o
cmake -S . -B harness-build -G Ninja -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=OFF -DJPEGXL_ENABLE_BENCHMARK=OFF -DJPEGXL_ENABLE_EXAMPLES=OFF -DJPEGXL_ENABLE_FUZZERS=ON -DJPEGXL_ENABLE_MANPAGES=OFF -DJPEGXL_ENABLE_SJPEG=OFF -DJPEGXL_ENABLE_TOOLS=OFF -DJPEGXL_ENABLE_VIEWERS=OFF -DJPEGXL_ENABLE_SKCMS=OFF -DJPEGXL_FORCE_SYSTEM_BROTLI=ON -DJPEGXL_FORCE_SYSTEM_HWY=ON -DJPEGXL_FUZZER_LINK_FLAGS="$PWD/harness-build/harness_main.o" -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build harness-build --target djxl_fuzzer --parallel 2 --verbose
